### ISSUE TITLE
[Initiative] Research Protobufs

### ISSUE THREAD

**Issue by benliao1** [pioneers/dawn#2]
Understand how protobufs are currently used to transfer data between Dawn and Runtime, then research how varying-length payloads could be sent to support a dashboard-like feature. Runtime would only have to send device data that the student wants to see / requests to see.

**Comment by lawrencechen14** [comment]
From reading through the documentation, it seems that protobufs already support varying length payloads through the `required`, `optional`, and `repeated` field modifiers. Since only the `required` fields are mandated to be sent, the protobufs already define a minimum set of data that Runtime needs to send to Dawn, while the `optional` and `repeated` fields do not have to be sent, thus reducing bandwidth if requested.

To create this data filter between Dawn and Runtime, all potential data fields should be included in `runtime.proto` in Dawn, as well as the corresponding `.proto` file in Runtime, with filterable fields being `optional` and non-filterable fields being `required`. Dawn will have a new frontend component to filter what data Runtime sends to it, and Dawn will send those preferences through Ansible (and through a new message defined in `ansible.proto`). Runtime will then store the filtering preferences and send the selected data fields to Dawn.
