### ISSUE TITLE
Implementing Challenge Input UI

### ISSUE THREAD

**Issue by HaileyJang** [pioneers/dawn#59]
Implementing Challenge Input UI + Backend for Runtime-Dawn Integration. 

Approximate steps are:  
- [ ] Write a new handler (Sagas & Runtime.ts)	
- [ ] Add a new tab in the editor for code challenges
- [ ] Create a new modal that takes in function inputs and display function outputs (React component)

**Comment by HaileyJang** [comment]
For clarification, is this right? 

Dawn -> Runtime : the student code + inputs that students want to test 
Runtime -> Dawn : the outputs from the inputs that they requested

**Comment by ewc340** [comment]
Related issues: #22 #30

**Comment by ewc340** [comment]
> For clarification, is this right?
> 
> Dawn -> Runtime : the student code + inputs that students want to test (and we are sending them over by specific challenges or just as one big protobuf?)
> Runtime -> Dawn : the outputs from the inputs that they requested

Yea, that looks correct.

**Comment by ewc340** [comment]
Here is a possible more detailed solution to what we want to do for this issue (only the UI for now, will update with Redux, sagas, and Runtime part later):

## UI portion:
**There will need to be a lot of work done here, and most of it will involve working with `Editor.tsx`. Although we haven't refactored that component yet to React Hooks, we will have work with it for now.**

Remember to first create a new branch off of `dev`.  Make sure there are also no lingering changes from your current branch.
```
git checkout dev
git checkout -b <insert branch name here>
```

1. We need to incorporate tabs into the editor so that the students can toggle between editors for their robot code and the code challenges. This means we are now hardcoding 2 files to the editor, each one mapped to a tab. In the future, we may want to include the ability to add a variable number of files. 
To achieve the tabbing behavior, fortunately `React-Bootstrap` has some nice tab components we can take advantage of, see [here](https://react-bootstrap-v3.netlify.app/components/tabs/). Essentially, we need add the following right after the forms and before `ConsoleOutput` in `Editor.tsx`:

```typescript
<Tabs defaultActiveKey={1} id="editor-tabs">
  // NOTE: In the future, we may want to make the names of the files changable, since the title of tab should vary based on student's preference so we will need to keep track of that
  <Tab eventKey={1} title="student_code.py">
    {<AceEditor />} // should be AceEditor for student code (this is currently what is in the code already)
  </Tab>
  <Tab eventKey={2} title="code_challenges.py">
    {<AceEditor />} // should be AceEditor for code challenges
  </Tab>
</Tabs>;
```

For the `AceEditor`, most of the props should be the same with exception of the `value` (will get more into this later), which should be the either the student code or code challenge code.

2. Now we focus on creating the modal that will take in code challenge function inputs and receive outputs. In the component `DNav.tsx` we need to add a new `TooltipButton` in the `ButtonGroup`. Something like the following:

```typescript
<TooltipButton
  placement="bottom"
  text="Check code challenges"
  bsStyle="info"
  onClick={<will need to implement this to toggle a modal>}
  id="check-code-challenges"
  glyph="<look for a nice looking glyph relating to code challenges :)>"
  disabled={false}
/>
```

3. For the `onClick` handler, above it should be similar to the 2 toggle modal functions in the component. Make sure to declare a new state variable and create the new toggle function.

4. Next, we'll focus on creating the actual modal. Create a new file, maybe something like `CheckCodeChallengesModal.tsx` and create a new functional component with the same name as the file. The design of the form should be something where we have 2 columns, the left one should have an input specifying the function name the student wants to test, the right one should have an input box, but a plus next to it that will spawn more boxes if a function has multiple inputs. Then below the 2 columns, there should be another plus button that will allow the student specify multiple functions and inputs. Then below that, we can probably have a results box containing the function name and the corresponding outputs.
 

More to come with the Redux, sagas, and Runtime stuff...
